services:
  php:
    volumes:
    - ./:/app
    image: composer:2.2

  install:
    volumes:
    - ./:/app
    image: composer:2.2
    command: composer install

  phpunit:
    volumes:
    - ./:/app
    image: composer:2.2
    command: composer phpunit

  test:
    volumes:
    - ./:/app
    image: composer:2.2
    command: composer run tests

  fixcs:
    volumes:
    - ./:/app
    image: composer:2.2
    command: composer run fix-cs
